apiVersion: v1
kind: ConfigMap
metadata:
    name: index-html-configmap
data:
    index.html: |
        <html>   
        <h1>Welcome to Kubernetes!</h1>
        </br>
        </html>
        <h1>This web page is hosted on a Pod running Nginx</h1>
        </html>
